### ISSUE TITLE
Some breaking times are wrong

### ISSUE THREAD

**Issue by veprogames** [veprogames/mt-100mts#5]
Example:

When the node `mts_bedrock:bedrock` defines the groups `{bedrocky = 1}` and a tool has groupcaps for `{cracky = {...}}`, the tool can still break the bedrock in about 700 ms. Why can it be broken? The intended mechanism is that only tools that define groupcaps for bedrocky can break it, but I'm kind of lost here.

**Comment by veprogames** [comment]
Bedrock is unbreakable now by making it not pointable or diggable. It works, but a hypothetical late game bedrock breaker tool wouldn't work with this approach

**Comment by Skamiz** [comment]
the issue is in the hand definition, specifically:
`cracky = {
                uses = 0,
                times = {[0] = 0.7, [1] = 1.4, [2] = 4, [3] = 16}
            }`
You are defining a digging time for a group rating of 0. And what do you know? Bedrocks cracky rating is also zero! (as in, it's not considered to be in that group)
Thus bedrock is digable by hand.

I have never seen this before, but I suppose the it kind of makes sense for it to work this way.

**Comment by veprogames** [comment]
That makes sense, also considering that the groupcaps definition of the hand (":") seems to merge with the current tool you're holding. I got it working correctly now in dev.
